<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [ ]:
# https://www.kaggle.com/prateekmaj21/tf-idf-in-python

In [1]:
text=["kolkata big city india trade",
      "mumbai financial capital india",
      "delhi capital india",
      "kolkata capital colonial times",
     "bangalore tech hub india software",
      "mumbai hub trade commerce stock exchange","kolkata victoria memorial","delhi india gate",
      "mumbai gate way india trade business","delhi red fort india","kolkata metro oldest india",
      "delhi metro largest metro network india"]


In [2]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
#using the count vectorizer
count = CountVectorizer(ngram_range = (1,3))
# count = CountVectorizer(ngram_range = (1,1))
word_count=count.fit_transform(text,)
print(word_count)

  (0, 47)	1
  (0, 3)	1
  (0, 11)	1
  (0, 42)	1
  (0, 88)	1
  (0, 48)	1
  (0, 4)	1
  (0, 12)	1
  (0, 45)	1
  (0, 49)	1
  (0, 5)	1
  (0, 13)	1
  (1, 42)	1
  (1, 67)	1
  (1, 29)	1
  (1, 7)	1
  (1, 68)	1
  (1, 30)	1
  (1, 10)	1
  (1, 69)	1
  (1, 31)	1
  (2, 42)	1
  (2, 7)	1
  (2, 10)	1
  (2, 19)	1
  :	:
  (9, 27)	1
  (9, 80)	1
  (10, 47)	1
  (10, 42)	1
  (10, 60)	1
  (10, 76)	1
  (10, 52)	1
  (10, 65)	1
  (10, 77)	1
  (10, 53)	1
  (10, 66)	1
  (11, 42)	1
  (11, 19)	1
  (11, 60)	2
  (11, 56)	1
  (11, 74)	1
  (11, 24)	1
  (11, 61)	1
  (11, 57)	1
  (11, 63)	1
  (11, 75)	1
  (11, 25)	1
  (11, 62)	1
  (11, 58)	1
  (11, 64)	1


In [4]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)

df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"]) 

In [6]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])

idf_weights
india                        1.262364
kolkata                      1.955511
delhi                        1.955511
mumbai                       2.178655
capital                      2.178655
...                               ...
exchange                     2.871802
delhi red fort               2.871802
delhi red                    2.871802
kolkata capital colonial     2.871802
way india trade              2.871802

[97 rows x 1 columns]

In [8]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)


tfidf
financial                 0.375774
financial capital         0.375774
financial capital india   0.375774
mumbai financial capital  0.375774
mumbai financial          0.375774
...                            ...
fort india                0.000000
fort                      0.000000
exchange                  0.000000
delhi red fort            0.000000
way india trade           0.000000

[97 rows x 1 columns]

Задание 1. Реализовать tfidf датасета 
https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset?datasetId=483&sortBy=voteCount

In [9]:
!pip install scikit-plot

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 6.6 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
tensorflow 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.0 which is incompatible.


In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import scipy as sp
import string
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

import nltk
import scikitplot as skplt
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
STOPWORDS = stopwords.words('english')

data=pd.read_csv('spam.csv', encoding = "ISO-8859-1")
data=data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
data=data.rename({'v1':'Class','v2':'Message'},axis=1)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^0-9a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = " ".join(word for word in text.split() if word not in STOPWORDS)
    return text
  
data['clean_text'] = data['Message'].apply(clean_text)
data.head()


X = data['clean_text']
y = data['Class']

# importing the PorterStemmer
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize,word_tokenize
ps=PorterStemmer
# words=word_tokenize('clean_text')

#importing the CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#lemmatizer=WordNetLemmatizer()


#define a function to get rid of stopwords present in the messages
def message_text_process(mess):
    # Check characters to see if there are punctuations 
    no_punctuation=[char for char in mess if char not in string.punctuation]
    # now form the sentence
    no_punctuation=''.join(no_punctuation)
    # Now eliminate any stopwords
    return[word for word in no_punctuation.split() if word.lower() not in stopwords.words('english')]

# to verify that function is working


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vasilijpancenko/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/vasilijpancenko/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/vasilijpancenko/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [11]:
data['Message'].head(5).apply(message_text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: Message, dtype: object

In [12]:
# start text processing with vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

#function for the model building and prediction
def Model(model, X, y):
#training and testing the data
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=30)
    # model building using CountVectorizer and TfidfTransformer
    pipeline_model = Pipeline([('vect', CountVectorizer(ngram_range = (1,3))),
                              ('tfidf', TfidfTransformer()),
                              ('clf', model)])
    pipeline_model.fit(x_train, y_train)
    
    


    y_pred = pipeline_model.predict(x_test)
    y_probas =pipeline_model.predict_proba(x_test)
    # skplt.metrics.plot_roc(y_test,y_probas,figsize=(12,8),title_fontsize=12,text_fontsize=16)
    # plt.show()
    # skplt.metrics.plot_precision_recall(y_test,y_probas,figsize=(12,8),title_fontsize=12,text_fontsize=16)
    # plt.show()
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
    print("Classification Report is:\n",classification_report(y_test, y_pred))
    print('Accuracy:', pipeline_model.score(x_test, y_test)*100)
    # print("Training Score:\n",pipeline_model.score(x_train,y_train)*100)


In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
Model(model, X, y)

Confusion Matrix:
 [[1219    1]
 [  83   90]]
Classification Report is:
               precision    recall  f1-score   support

         ham       0.94      1.00      0.97      1220
        spam       0.99      0.52      0.68       173

    accuracy                           0.94      1393
   macro avg       0.96      0.76      0.82      1393
weighted avg       0.94      0.94      0.93      1393

Accuracy: 93.96984924623115
